services:
  app:
    image: 'backstage:latest'
    build:
      context: .
    container_name: backstage_app
    ports:
      - 3000:3000
      - 7007:7007
    depends_on:
      - postgres
    env_file: ".env"

  postgres:
    image: postgres:17.2-alpine3.20
    container_name: pg_host_backstage
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=backstage
      - POSTGRES_USER=backstage
