cluster_name="${{ values.appName }}"
cloud_provider="AWS"
instance_size="${{values.instanceSize}}"
region="${{ values.region}}"
dbuser="${{ values.databaseUser}}"
project_id = "${{ values.project_id }}"
ip_address = "0.0.0.0"
