apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: mongodb-database-terraform-template
  title: Atlas Production Terraform Template
  description: Scaffold a GitHub repository containing database configuration and Terraform YAML
  tags: 
    - recommended

spec:
  owner: developers
  type: service
  
  parameters:
    - title: Database Configuration
      required:
        - appName
      properties:
        appName:
          title: Production Application Name
          type: string
        projectId:
          title: ID of the Atlas Project for the Cluster
          type: string
        region:
          title: AWS region
          default: US_EAST_1
          type: string
          enum:
            - US_EAST_1
            - US_WEST_1
        instanceSize:
          title: Database Name
          type: string
          default: M10
          enum:
            - M10
            - M20
            - M30
        databaseUser:
          title: Database Username
          type: string
          default: admin
        databasePass:
          title: Database user password
          type: string
          ui:field: Secret
        public_key:
          title: Atlas Public API Key
          type: string
          ui:field: Secret
        private_key:
          title: Atlas Private API Key
          type: string
          ui:field: Secret
        repo_owner:
          title: App Team Repo Owner
          type: string

          

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutTemplating:
          - .github/workflows/*
          - .gitignore
        values:
          appName: ${{ parameters.appName }}
          region: ${{ parameters.region }}
          instanceSize: ${{ parameters.instanceSize }}
          databaseUser: ${{ parameters.databaseUser }}
          databasePass: ${{ secrets.databasePass }}
          projectId: ${{ parameters.projectId }}

    - id: create
      name: Create Repo
      action: github:repo:create
      input:
        allowedHosts: ['github.com']
        defaultBranch: "main"
        repoUrl: github.com?repo=${{ parameters.appName }}&owner=${{parameters.repo_owner}}
        secrets:
          MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.public_key }}
          MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.private_key }}
          db_password: ${{ parameters.databasePass }}
        repoVariables:
          project_id: ${{ parameters.project_id }}

    - id: push
      name: Push content to repo
      action: github:repo:push
      input:
        allowedHosts: [ 'github.com' ]
        defaultBranch: "main"
        repoUrl: github.com?repo=${{ parameters.appName }}&owner=${{parameters.repo_owner}}

    - id: pull-request
      action: publish:github:pull-request
      name: Create a pull request for Terraform content
      input:
        repoUrl: github.com?repo=${{ parameters.appName }}&owner=${{ parameters.repo_owner }}
        branchName: terraform
        title: Create my new db
        description: This PR is really good
        targetBranchName: main
        targetPath: apps

    - action: fs:delete
      id: deleteFiles
      name: Delete files
      input:
         files:
          - catalog-info.yaml
          - .github/workflows/terraform.yaml

    - id: register
      name: Register
      action: catalog:register
      input:
        catalogInfoUrl: "https://github.com/${{parameters.repo_owner}}/${{ parameters.appName }}/blob/main/catalog-info.yaml"


